# CloudCannon Configuration
paths:
  uploads: assets

# Force Content Editor on all HTML files
collections_config:
  pages:
    path: /
    output: true
    filter:
      base_ext:
        - .html

_enabled_editors:
  - content
  - source